project_id = "iuwxtoznnuuclxseuxoi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
pool_size = 20
max_rows = 1000

[db]
enabled = true
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[edge_runtime]
enabled = true
port = 54326

[auth]
enabled = true
port = 54327

# Edge functions now require JWT verification for security
# Only process-openai-ocr remains public for external processing workflows
[functions.process-openai-ocr]
verify_jwt = false