// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuwxtoznnuuclxseuxoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1d3h0b3pubnV1Y2x4c2V1eG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzE0ODIsImV4cCI6MjA3MDUwNzQ4Mn0.JRHaNH3oT4DudmUlZDGhE-GAHcyVeso9kiiXahEl8BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});